INSERT INTO subjects (subject_name, year_offered) VALUES 
('Accounting', 'I'), 
('Afrikaans and Netherlandic Studies', 'I'), 
('African Languages', 'I'), 
('Anthropology', 'I'), 
('Biochemistry', 'I'), 
('Microbiology', 'I'), 
('Biotechnology Innovation Centre', 'I'), 
('Botany', 'I'), 
('Business School', 'I'), 
('Centre for Higher Education Research, Teaching and Learning', 'I'), 
('Chemistry', 'I'), 
('Chinese', 'I'), 
('Classical Studies', 'I'), 
('Computer Science', 'I'), 
('Drama', 'I'), 
('Economics and Economics History', 'I'), 
('Education', 'I'), 
('English Language and Linguistics', 'I'), 
('Environmental Science', 'I'), 
('Extended Studies Unit', 'I'), 
('Fine Art', 'I'), 
('French', 'I'), 
('Geography', 'I'), 
('Geology', 'I'), 
('German', 'I'), 
('History', 'I'), 
('Human Kinetics and Ergonomics', 'I'), 
('Ichthyology and Fisheries Science', 'I'), 
('Information Systems', 'I'), 
('Journalism & Media Studies', 'I'), 
('Law', 'I'), 
('Literary Studies in English', 'I'), 
('Management', 'I'), 
('Mathematics (Pure and Applied)', 'I'), 
('Modern Fiction', 'I'), 
('Music & Musicology', 'I'), 
('Pharmacy', 'I'), 
('Philosophy', 'I'), 
('Physics and Electronics', 'I'), 
('Political and International Studies', 'I'), 
('Psychology', 'I'), 
('School of Languages', 'I'), 
('Sociology', 'I'), 
('Statistics', 'I'), 
('Zoology and Entomology', 'I');

